/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-10 02:53:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/class/code/server/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSP_PROJECT_JALANG-I/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1699496628000L));
    _jspx_dependants.put("/WEB-INF/views/inc/ad.jsp", Long.valueOf(1699496628000L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1699498504000L));
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1699496628000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1699496628000L));
    _jspx_dependants.put("/WEB-INF/views/inc/side.jsp", Long.valueOf(1699496628000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Logis Bootstrap Template - Index</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/glightbox/css/glightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: Logis\r\n");
      out.write("  * Updated: Sep 18 2023 with Bootstrap v5.3.2\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/logis-bootstrap-logistics-website-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/purecounter/purecounter_vanilla.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/aos/aos.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Header ======= -->\r\n");
      out.write("<header id=\"header\" class=\"header d-flex align-items-center fixed-top\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container-fluid container-xl d-flex align-items-center justify-content-between\">\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"/jr/index.do\" class=\"logo d-flex align-items-center\"> <!-- Uncomment the line below if you also wish to use an image logo -->\r\n");
      out.write("			<!-- <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/logo.png\" alt=\"\"> -->\r\n");
      out.write("			<h1>자랑이</h1>\r\n");
      out.write("		</a> \r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			<i class=\"mobile-nav-toggle mobile-nav-show bi bi-list\"></i> \r\n");
      out.write("			<i class=\"mobile-nav-toggle mobile-nav-hide d-none bi bi-x\"></i>\r\n");
      out.write("		<nav id=\"navbar\" class=\"navbar\">\r\n");
      out.write("			\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<span>자격증 조회</span> \r\n");
      out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<span>자격증 추천</span> \r\n");
      out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<span>교재 조회 및 맞춤 추천</span> \r\n");
      out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<span>학원 및 우리동네 학원</span> \r\n");
      out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<span>직업 정보</span> \r\n");
      out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<span>자유 게시판</span> \r\n");
      out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("				\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\" class=\"get-a-quote\">\r\n");
      out.write("						<span>메뉴</span> \r\n");
      out.write("					</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						<li><a href=\"#\" class=\"active\">기업 서비스</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			\r\n");
      out.write("		</nav>\r\n");
      out.write("		\r\n");
      out.write("		<!-- .navbar -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= <main id=\"main\"> 여기부터 집어넣기 ======= -->\r\n");
      out.write("  \r\n");
      out.write("    <main id=\"main\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- ======= Breadcrumbs ======= -->\r\n");
      out.write("    <div class=\"breadcrumbs\">\r\n");
      out.write("      <div class=\"page-header d-flex align-items-center\" style=\"background-image: url('");
      out.print(request.getContextPath() );
      out.write("/resources/img/page-header.jpg');\">\r\n");
      out.write("        <div class=\"container position-relative\">\r\n");
      out.write("          <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-6 text-center\">\r\n");
      out.write("              <h2>로그인</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <ol>\r\n");
      out.write("            <li><a href=\"/jr/index.do\">Home</a></li>\r\n");
      out.write("            <li>로그인</li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div><!-- End Breadcrumbs -->\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <!-- ======= Get a Quote Section ======= -->\r\n");
      out.write("    <section id=\"get-a-quote\" class=\"get-a-quote\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"container\" data-aos=\"fade-up\" >\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row g-0\" style=\"display: flex; justify-content: center;\">\r\n");
      out.write("		\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-7\" style=\"width: 500px;\">\r\n");
      out.write("            <form action=\"/jr/user/login.do\" method=\"post\" class=\"php-email-form\">\r\n");
      out.write("              <h1 style=\"text-align: center;\">로그인</h1>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"row gy-4\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <input type=\"text\" name=\"id\" class=\"form-control\" placeholder=\"아이디를 입력해주세요\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <input type=\"password\" name=\"pw\" class=\"form-control\" placeholder=\"비밀번호를 입력해주세요\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("				\r\n");
      out.write("				<div style=\"display: flex; justify-content: right;\">\r\n");
      out.write("					<a href=\"/toy/user/register.do\">아이디 찾기</a> <p> &vert; </p>\r\n");
      out.write("					<a href=\"/toy/user/register.do\"> 비밀번호 찾기</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("                <div class=\"col-md-12 text-center\">\r\n");
      out.write("                  <div class=\"loading\">Loading</div>\r\n");
      out.write("                  <div class=\"error-message\"></div>\r\n");
      out.write("                  <div class=\"sent-message\">Your quote request has been sent successfully. Thank you!</div>\r\n");
      out.write("\r\n");
      out.write("                  <button type=\"submit\">로그인</button>\r\n");
      out.write("                  <div><a href=\"/toy/user/register.do\">회원가입</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          </div><!-- End Quote Form -->\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("	            <form action=\"/jr/user/login.do\" method=\"post\" class=\"php-email-form\">\r\n");
      out.write("	            <input type=\"hidden\" name=\"id\" value=\"test1\">\r\n");
      out.write("	            <input type=\"hidden\" name=\"pw\" value=\"1234\">\r\n");
      out.write("	            <button type=\"submit\">일반</button>\r\n");
      out.write("            	</form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("	            <form action=\"/jr/user/login.do\" method=\"post\" class=\"php-email-form\">\r\n");
      out.write("	            <input type=\"hidden\" name=\"id\" value=\"admin\">\r\n");
      out.write("	            <input type=\"hidden\" name=\"pw\" value=\"1234\">\r\n");
      out.write("	            <button type=\"submit\">관리자</button>\r\n");
      out.write("            	</form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Get a Quote Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- ======= </main> 까지 집어넣기 ======= -->\r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\" class=\"footer\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row gy-4\">\r\n");
      out.write("        <div class=\"col-lg-5 col-md-12 footer-info\">\r\n");
      out.write("          <a href=\"index.html\" class=\"logo d-flex align-items-center\">\r\n");
      out.write("            <span>Logis</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>\r\n");
      out.write("          <div class=\"social-links d-flex mt-4\">\r\n");
      out.write("            <a href=\"#\" class=\"twitter\"><i class=\"bi bi-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"facebook\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"instagram\"><i class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"linkedin\"><i class=\"bi bi-linkedin\"></i></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-2 col-6 footer-links\">\r\n");
      out.write("          <h4>Useful Links</h4>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#\">About us</a></li>\r\n");
      out.write("            <li><a href=\"#\">Services</a></li>\r\n");
      out.write("            <li><a href=\"#\">Terms of service</a></li>\r\n");
      out.write("            <li><a href=\"#\">Privacy policy</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-2 col-6 footer-links\">\r\n");
      out.write("          <h4>Our Services</h4>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">Web Design</a></li>\r\n");
      out.write("            <li><a href=\"#\">Web Development</a></li>\r\n");
      out.write("            <li><a href=\"#\">Product Management</a></li>\r\n");
      out.write("            <li><a href=\"#\">Marketing</a></li>\r\n");
      out.write("            <li><a href=\"#\">Graphic Design</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-3 col-md-12 footer-contact text-center text-md-start\">\r\n");
      out.write("          <h4>Contact Us</h4>\r\n");
      out.write("          <p>\r\n");
      out.write("            A108 Adam Street <br>\r\n");
      out.write("            New York, NY 535022<br>\r\n");
      out.write("            United States <br><br>\r\n");
      out.write("            <strong>Phone:</strong> +1 5589 55488 55<br>\r\n");
      out.write("            <strong>Email:</strong> info@example.com<br>\r\n");
      out.write("          </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container mt-4\">\r\n");
      out.write("      <div class=\"copyright\">\r\n");
      out.write("        &copy; Copyright <strong><span>Logis</span></strong>. All Rights Reserved\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"credits\">\r\n");
      out.write("        <!-- All the links in the footer should remain intact. -->\r\n");
      out.write("        <!-- You can delete the links only if you purchased the pro version. -->\r\n");
      out.write("        <!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/logis-bootstrap-logistics-website-template/ -->\r\n");
      out.write("        Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("  <!-- End Footer -->");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"scroll-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"preloader\"></div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("  	\r\n");
      out.write("  	#ad {\r\n");
      out.write("  		position: fixed;\r\n");
      out.write("  		width: 200px;\r\n");
      out.write("	    top: 400px; \r\n");
      out.write("	    right: 0; \r\n");
      out.write("	    background-color: lightblue;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: 1px solid #000;\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	#ad img{\r\n");
      out.write("  		width: 180px;\r\n");
      out.write("  		background-size: cover;\r\n");
      out.write("  	} \r\n");
      out.write("  	\r\n");
      out.write("  </style>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"ad\">\r\n");
      out.write("  	<div><img alt=\"\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/cat01_small.jpg\"></div>\r\n");
      out.write("  	<div><a href=\"#\">자격증</a></div>\r\n");
      out.write("  	<div><a href=\"#\">내메뉴</a></div>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("  console.log(window.location.href);\r\n");
      out.write("\r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("	    // 초기 로드 시와 창 크기 변경 시에 함수를 실행\r\n");
      out.write("	    adjustAdVisibility();\r\n");
      out.write("\r\n");
      out.write("	    // 창 크기 변경 이벤트를 모니터링\r\n");
      out.write("	    $(window).on(\"resize\", function() {\r\n");
      out.write("	        adjustAdVisibility();\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    function adjustAdVisibility() {\r\n");
      out.write("	        var windowWidth = $(window).width();\r\n");
      out.write("\r\n");
      out.write("	        \r\n");
      out.write("	        \r\n");
      out.write("	        if (windowWidth <= 1500) {\r\n");
      out.write("	            // id=\"ad\"인 div 태그 숨김 또는 제거\r\n");
      out.write("	            $(\"#ad\").hide();\r\n");
      out.write("	            // 또는 $(\"#ad\").remove();\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // 창의 너비가 1700px 이상이거나 URL이 \"http://localhost:8090/jr/index.do\"와 일치하면 id=\"ad\"인 div 태그 다시 표시\r\n");
      out.write("	            $(\"#ad\").show();\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  </script>");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("  	\r\n");
      out.write("  	#side {\r\n");
      out.write("  		transform: translate;\r\n");
      out.write("  		position: fixed;\r\n");
      out.write("  		width: 200px;\r\n");
      out.write("	    top: 295px; \r\n");
      out.write("	    left: 0; \r\n");
      out.write("	    background-color: lightblue;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: 1px solid #000;\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  \r\n");
      out.write("  	\r\n");
      out.write("  </style>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"side\">\r\n");
      out.write("  	<div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write(" 	 <div class=\"accordion-item\">\r\n");
      out.write("	    <h2 class=\"accordion-header\">\r\n");
      out.write("	      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseOne\" aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n");
      out.write("	        자격증 조회\r\n");
      out.write("	      </button>\r\n");
      out.write("	    </h2>\r\n");
      out.write("	    <div id=\"collapseOne\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("	      <div class=\"accordion-body\">\r\n");
      out.write("	        <strong>1</strong> \r\n");
      out.write("	        <code>.accordion-body</code>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	  <div class=\"accordion-item\">\r\n");
      out.write("	    <h2 class=\"accordion-header\">\r\n");
      out.write("	      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("	        자격증 추천\r\n");
      out.write("	      </button>\r\n");
      out.write("	    </h2>\r\n");
      out.write("	    <div id=\"collapseTwo\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("	      <div class=\"accordion-body\">\r\n");
      out.write("			<strong>2</strong> \r\n");
      out.write("	        <code>.accordion-body</code>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	  <div class=\"accordion-item\">\r\n");
      out.write("	    <h2 class=\"accordion-header\">\r\n");
      out.write("	      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("	        교재 조회 및 맞춤 추천\r\n");
      out.write("	      </button>\r\n");
      out.write("	    </h2>\r\n");
      out.write("	    <div id=\"collapseThree\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("	      <div class=\"accordion-body\">\r\n");
      out.write("	        <strong>3</strong> \r\n");
      out.write("	        <code>.accordion-body</code>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	  <div class=\"accordion-item\">\r\n");
      out.write("	    <h2 class=\"accordion-header\">\r\n");
      out.write("	      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapse4\" aria-expanded=\"false\" aria-controls=\"collapse4\">\r\n");
      out.write("	        학원 및 우리동네 학원\r\n");
      out.write("	      </button>\r\n");
      out.write("	    </h2>\r\n");
      out.write("	    <div id=\"collapse4\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("	      <div class=\"accordion-body\">\r\n");
      out.write("	      	<strong>4</strong> \r\n");
      out.write("	        <code>.accordion-body</code>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	\r\n");
      out.write("  	<div class=\"accordion-item\">\r\n");
      out.write("	    <h2 class=\"accordion-header\">\r\n");
      out.write("	      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapse5\" aria-expanded=\"false\" aria-controls=\"collapse5\">\r\n");
      out.write("	        직업 정보\r\n");
      out.write("	      </button>\r\n");
      out.write("	    </h2>\r\n");
      out.write("	    <div id=\"collapse5\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("	      <div class=\"accordion-body\">\r\n");
      out.write("	      	<strong>5</strong> \r\n");
      out.write("	        <code>.accordion-body</code>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("  	  <div class=\"accordion-item\">\r\n");
      out.write("	    <h2 class=\"accordion-header\">\r\n");
      out.write("	      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapse6\" aria-expanded=\"false\" aria-controls=\"collapse6\">\r\n");
      out.write("	        자유 게시판\r\n");
      out.write("	      </button>\r\n");
      out.write("	    </h2>\r\n");
      out.write("	    <div id=\"collapse6\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("	      <div class=\"accordion-body\">\r\n");
      out.write("	      	<strong>6</strong> \r\n");
      out.write("	        <code>.accordion-body</code>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	 </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("\r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("	    // 초기 로드 시와 창 크기 변경 시에 함수를 실행\r\n");
      out.write("	    sideBar();\r\n");
      out.write("\r\n");
      out.write("	    // 창 크기 변경 이벤트를 모니터링\r\n");
      out.write("	    $(window).on(\"resize\", function() {\r\n");
      out.write("	    	sideBar();\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    function sideBar() {\r\n");
      out.write("	        var windowWidth = $(window).width();\r\n");
      out.write("	        var currentURL = window.location.href;\r\n");
      out.write("\r\n");
      out.write("	        \r\n");
      out.write("	        \r\n");
      out.write("	        if (windowWidth <= 1500 || currentURL == \"http://localhost:8090/jr/index.do\") {\r\n");
      out.write("	            // id=\"ad\"인 div 태그 숨김 또는 제거\r\n");
      out.write("	            $(\"#side\").hide();\r\n");
      out.write("	            // 또는 $(\"#ad\").remove();\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // 창의 너비가 1700px 이상이거나 URL이 \"http://localhost:8090/jr/index.do\"와 일치하면 id=\"ad\"인 div 태그 다시 표시\r\n");
      out.write("	            $(\"#side\").show();\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  </script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <Script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </Script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(83,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lv == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<li class=\"dropdown\">\r\n");
          out.write("					<a href=\"#\">\r\n");
          out.write("						<span>마이 메뉴</span> \r\n");
          out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
          out.write("					</a>\r\n");
          out.write("					<ul>\r\n");
          out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
          out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
          out.write("					</ul>\r\n");
          out.write("				</li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(96,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lv == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<li class=\"dropdown\">\r\n");
          out.write("					<a href=\"#\">\r\n");
          out.write("						<span>관리 메뉴</span> \r\n");
          out.write("						<i class=\"bi bi-chevron-down dropdown-indicator\"></i>\r\n");
          out.write("					</a>\r\n");
          out.write("					<ul>\r\n");
          out.write("						<li><a href=\"#\">자유 게시판</a></li>\r\n");
          out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
          out.write("					</ul>\r\n");
          out.write("				</li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/inc/header.jsp(114,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"/jr/user/login.do\" class=\"active\">로그인</a></li>\r\n");
          out.write("						<li><a href=\"#\" class=\"active\">회원가입</a></li>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/inc/header.jsp(118,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li></li>\r\n");
          out.write("						<li><a href=\"/jr/user/logout.do\" class=\"active\">로그아웃</a></li>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
